/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and returns a JWT token. Each registered user gets a fully isolated sandbox — events and bookings are private to their account.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthInput"];
                };
            };
            responses: {
                /** @description Account created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Validation error — invalid email format or password too short, or email already registered */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Validation failed */
                            error?: string;
                            details?: {
                                /** @example email */
                                field?: string;
                                /** @example A valid email is required */
                                message?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with existing credentials
         * @description Authenticates a user and returns a JWT token. Store the token and send it as a Bearer token in the Authorization header on all subsequent requests.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthInput"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Wrong password or validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Invalid credentials */
                            error?: string;
                        };
                    };
                };
                /** @description No account found for this email */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example User not found */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the currently authenticated user
         * @description Validates the bearer token and returns the decoded user identity. Useful for verifying a token is still valid.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token is valid — returns user identity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Missing or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Unauthorized */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all bookings
         * @description Returns a paginated list of all bookings, each including full event details.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filter bookings by event ID
                     * @example 1
                     */
                    eventId?: number;
                    /**
                     * @description Filter by booking status
                     * @example confirmed
                     */
                    status?: "confirmed" | "cancelled";
                    /** @description Page number */
                    page?: number;
                    /** @description Number of bookings per page */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of bookings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Booking"][];
                            pagination?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a booking (buy tickets)
         * @description Books tickets for an event. The service will:
         *     1. Verify the event exists
         *     2. Check sufficient seats are available
         *     3. Calculate the total price
         *     4. Generate a unique booking reference (EVT-XXXXXX)
         *     5. Atomically create the booking and decrement available seats
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "eventId": 1,
                     *       "customerName": "Priya Sharma",
                     *       "customerEmail": "priya.sharma@email.com",
                     *       "customerPhone": "+91-9876543210",
                     *       "quantity": 2
                     *     }
                     */
                    "application/json": components["schemas"]["CreateBookingInput"];
                };
            };
            responses: {
                /** @description Booking confirmed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                            /** @example Booking confirmed! */
                            message?: string;
                        };
                    };
                };
                /** @description Validation error or insufficient seats */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/ref/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up a booking by reference code
         * @description Retrieves a booking using the unique booking reference (e.g. EVT-A1B2C3).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Booking reference code
                     * @example EVT-A1B2C3
                     */
                    ref: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "error": "Booking with reference \"EVT-XYZ123\" not found"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single booking by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numeric booking ID
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Booking"];
                        };
                    };
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Cancel a booking
         * @description Cancels (permanently deletes) a booking and atomically restores the
         *     released seats back to the event's `availableSeats` count.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numeric ID of the booking to cancel
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking cancelled and seats restored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Booking cancelled */
                            message?: string;
                        };
                    };
                };
                /** @description Booking not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all events
         * @description Returns a paginated list of events. Supports filtering by category, city, and free-text search.
         */
        get: {
            parameters: {
                query?: {
                    /**
                     * @description Filter events by category
                     * @example Conference
                     */
                    category?: "Conference" | "Concert" | "Sports" | "Workshop" | "Festival";
                    /**
                     * @description Filter events by city
                     * @example Bangalore
                     */
                    city?: string;
                    /**
                     * @description Search events by title, description, or venue
                     * @example summit
                     */
                    search?: string;
                    /** @description Page number */
                    page?: number;
                    /** @description Number of events per page */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Event"][];
                            pagination?: components["schemas"]["PaginationMeta"];
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new event
         * @description Creates an event. `availableSeats` is automatically set equal to `totalSeats`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "Tech Summit 2026",
                     *       "description": "A premier technology conference.",
                     *       "category": "Conference",
                     *       "venue": "Bangalore International Centre",
                     *       "city": "Bangalore",
                     *       "eventDate": "2026-06-15T09:00:00.000Z",
                     *       "price": 1500,
                     *       "totalSeats": 500,
                     *       "imageUrl": "https://example.com/banner.jpg"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateEventInput"];
                };
            };
            responses: {
                /** @description Event created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Event"];
                            /** @example Event created successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single event by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numeric ID of the event
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Event"];
                        };
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "error": "Event with id 99 not found"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Update an event */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numeric ID of the event to update
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventInput"];
                };
            };
            responses: {
                /** @description Event updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            data?: components["schemas"]["Event"];
                            /** @example Event updated successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an event
         * @description Permanently deletes an event and all associated bookings (cascade).
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Numeric ID of the event to delete
                     * @example 1
                     */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example Event deleted successfully */
                            message?: string;
                        };
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API is running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** Format: date-time */
                            timestamp?: string;
                            /** @example connected */
                            dbStatus?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public feature flags */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feature flag values */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            showExploreLinks?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthInput: {
            /**
             * Format: email
             * @example student@example.com
             */
            email: string;
            /** @example secret123 */
            password: string;
        };
        AuthResponse: {
            /** @example true */
            success?: boolean;
            /**
             * @description JWT bearer token — valid for 7 days. Pass as Authorization header on all protected routes.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token?: string;
            user?: {
                /** @example 42 */
                id?: number;
                /** @example student@example.com */
                email?: string;
            };
        };
        MeResponse: {
            /** @example true */
            success?: boolean;
            user?: {
                /** @example 42 */
                userId?: number;
                /** @example student@example.com */
                email?: string;
            };
        };
        Booking: {
            /** @example 1 */
            id?: number;
            /** @example 3 */
            eventId?: number;
            /** @example Priya Sharma */
            customerName?: string;
            /** @example priya.sharma@email.com */
            customerEmail?: string;
            /** @example +91-9876543210 */
            customerPhone?: string;
            /** @example 2 */
            quantity?: number;
            /**
             * Format: float
             * @example 3000
             */
            totalPrice?: number;
            /**
             * @example confirmed
             * @enum {string}
             */
            status?: "confirmed" | "cancelled";
            /** @example EVT-A1B2C3 */
            bookingRef?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            event?: components["schemas"]["Event"];
        };
        CreateBookingInput: {
            /** @example 1 */
            eventId: number;
            /** @example Priya Sharma */
            customerName: string;
            /**
             * Format: email
             * @example priya.sharma@email.com
             */
            customerEmail: string;
            /** @example +91-9876543210 */
            customerPhone: string;
            /** @example 2 */
            quantity: number;
        };
        Event: {
            /** @example 1 */
            id?: number;
            /** @example Tech Summit 2026 */
            title?: string;
            /** @example A premier technology conference bringing together industry leaders. */
            description?: string;
            /** @example Conference */
            category?: string;
            /** @example Bangalore International Centre */
            venue?: string;
            /** @example Bangalore */
            city?: string;
            /**
             * Format: date-time
             * @example 2026-06-15T09:00:00.000Z
             */
            eventDate?: string;
            /**
             * Format: float
             * @example 1500
             */
            price?: number;
            /** @example 500 */
            totalSeats?: number;
            /** @example 342 */
            availableSeats?: number;
            /** @example https://example.com/images/tech-summit.jpg */
            imageUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateEventInput: {
            /** @example Tech Summit 2026 */
            title: string;
            /** @example A premier technology conference. */
            description?: string;
            /** @example Conference */
            category: string;
            /** @example Bangalore International Centre */
            venue: string;
            /** @example Bangalore */
            city: string;
            /**
             * Format: date-time
             * @example 2026-06-15T09:00:00.000Z
             */
            eventDate: string;
            /** @example 1500 */
            price: number;
            /** @example 500 */
            totalSeats: number;
            /** @example https://example.com/banner.jpg */
            imageUrl?: string;
        };
        PaginationMeta: {
            /** @example 48 */
            total?: number;
            /** @example 1 */
            page?: number;
            /** @example 10 */
            limit?: number;
            /** @example 5 */
            totalPages?: number;
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Resource not found */
            error?: string;
        };
        ValidationErrorResponse: {
            /** @example false */
            success?: boolean;
            /** @example Validation failed */
            error?: string;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
